Repository open-sauced/intro, pull requests merged in 2023-10, with the labels that each got.

#67 added .take section to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, 🐛 bug

#80 Updated README to include translation info. Added i18n-guidelines.md
  README.md
  i18n-guidelines.md
Labels: documentation, good first issue

#84 feat: adds a section about Merging Conflicts
  11-understanding-merge-conflicts.md
  _layouts/sidebar.md
Labels: documentation, 💡 feature
